#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=0

if [[  $(cat /sys/class/power_supply/BAT0/status) = "Charging" ]]; then
  status=1
fi


status=$(( $status+(2**(( $capacity/25)+1)) ))


case $status in
  0) ;;
2) ;;
4) ;;
8) ;;
16) ;;
  1) ;;
3) ;;
5) ;;
9) ;;
17) ;;
esac




printf '%d (%s)' $capacity $(cat /sys/class/power_supply/BAT0/status) 
