#!/bin/sh

amixer_on=$(amixer sget Master | awk -F'\\]' '/Left:/ { print $2 }' | cut -c 3-)

current_volume=$(amixer sget Master | awk -F'[][]' '/Left:/ { print $2 }'  )

if [ $amixer_on = 'on' ] ; then
  icon='󰝟 '
else 
  icon='󰕾'
fi

echo $icon $current_volume
