#!/bin/sh

curr_network=$(nmcli -c no dev wifi | grep '^*' | awk '{ print $3 }')

if [[ ${curr_network} != "" ]] ; then
  
  connection_strength=$(nmcli -c no dev wifi | grep '^*' | awk '{ print $9 }')

  case $connection_strength in
    ▂___) connection_strength="󰤟 " 
    ;;
    ▂▄__) connection_strength="󰤢 " 
    ;;
    ▂▄▆_) connection_strength="󰤥 "
    ;;
    ▂▄▆█) connection_strength='󰤨 ';;
  esac
  echo $connection_strength $curr_network

  exit 0
fi

echo "No wifi"
