#!/bin/sh
station=$(ip addr | gawk '/state UP/ { device = $2 ; output = gsub(":", "",device); print device}')

network=$(iw dev $station link | gawk '/SSID:/ {print $2}' )

dbm=$(iw dev $station link | gawk '/signal:/ { print $2 }')

if [ $dbm -ge -40 ]; then
 symbol="󰤨 "
elif [ $dbm -le -40 ] && [ $dbm -gt -60 ]; then
  symbol="󰤥 "
elif [ $dbm -le -60 ] && [ $dbm -gt -80 ]; then
  symbol="󰤢 "
elif [ $dbm -le -80 ]; then
  symbol="󰤟 " 
fi

echo $symbol $network
